### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by vladislavivanistsev** [vilab-tartu/LOKT.02.048#2]
Please specify the requirements: version of python, GPAW, ASE, etc.

**Comment by kkaru** [comment]
I installed the latest packages for Ubuntu 17.04 on the VM, so:  jupyter notebook 5.2.2-1, Python 3.6.3 (2.7.14 is the default compiler for the OS, but I assigned 3.6.3 as default for jupyter notebooks), GPAW 1.3.0-2, ASE 3.15.0-1, IPython 5.5.0.

**Comment by MaksimMisin** [comment]
So basically you could write the following shell script:
```
#!/bin/bash
curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh  -p ~/opt/anaconda3 -b
export PATH=~/opt/anaconda3/bin:${PATH}
conda update -y conda
conda install -y jupyter ipython
conda install -c conda-forge -y ase 
pip install gpaw
```

Check if it works!

**Comment by kkaru** [comment]
I used apt and pip for everything instead of conda. Nothing was done manually on 17.10 and it works. Once we have the server, we can simply replicated the VM image.

**Comment by vladislavivanistsev** [comment]
Please install the packages for visualization. See http://lukaszmentel.com/blog/ase-jupyter-notebook/index.html

**Comment by kkaru** [comment]
There are multiple methods described there. The first one requires only native packages. I tested it and it works.
The following code block needs to be present:

```
from IPython.display import HTML
def atoms_to_html(atoms):
    'Return the html representation the atoms object as string'

    from tempfile import NamedTemporaryFile

    with NamedTemporaryFile('r+', suffix='.html') as ntf:
        atoms.write(ntf.name, format='html')
        ntf.seek(0)
        html = ntf.read()
    return html
```

Followingly, structures can be visualised by calling:

`HTML(atoms_to_html(molecule))`

where "molecule" is the ase.Atoms object to be visualized.
